package:
  name: openocd
  version: v0.9.0_44_g3edb157

source:
  git_rev: v0.9.0-44-g3edb157
  git_url: git://git.code.sf.net/p/openocd/code
  patches: 
    - relative-scripts.patch

build:
  number: 6

test:
  commands:
    - openocd -v

about:
  home: http://openocd.org/
  license: GPL
  summary: 'Free and Open On-Chip Debugging, In-System Programming and Boundary-Scan Testing'
