package:
  name: openocd
  version: v0.9.0_24_gd28ab08

source:
  git_rev: v0.9.0-24-gd28ab08
  git_url: git://git.code.sf.net/p/openocd/code

build:
  number: 1

requirements:
  build:
    - ncurses
    - boost
  run:
    - ncurses
    - boost

about:
  home: http://openocd.org/
  license: GPL
  summary: 'Free and Open On-Chip Debugging, In-System Programming and Boundary-Scan Testing'
