package:
  name: openocd
  version: git

source:
  git_rev: v0.9.0-118-g8697d82
  git_url: git://github.com/mithro/openocd.git
  patches: 
    - relative-scripts.patch

test:
  commands:
    - openocd -v
    - openocd -v 2>&1 | head -1 | grep -q -v dirty
    - openocd -v 2>&1 | head -1 | grep -q -- "-[0-9][0-9][0-9][0-9][0-9]-[0-9a-z]\+ "

about:
  home: http://openocd.org/
  license: GPL
  summary: 'Free and Open On-Chip Debugging, In-System Programming and Boundary-Scan Testing'
