package:
  name: openocd
  version: v0.9.0_118_g8697d82

source:
  git_rev: v0.9.0-118-g8697d82
  git_url: git://github.com/mithro/openocd.git
  patches: 
    - relative-scripts.patch

build:
  number: 1

test:
  commands:
    - openocd -v

about:
  home: http://openocd.org/
  license: GPL
  summary: 'Free and Open On-Chip Debugging, In-System Programming and Boundary-Scan Testing'
