package:
  name: openocd
  version: git

source:
  git_rev: master
  git_url: git://repo.or.cz/openocd.git
  patches:
    - digilent-arty.patch
    - fpga-program.patch

build:
  number: 0

test:
  commands:
    - openocd -v

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
