package:
  name: openocd
  version: git

source:
  git_rev: v0.9.0-247-g73b676c
  git_url: git://repo.or.cz/openocd.git
  patches: 
    - relative-scripts.patch

test:
  commands:
    - openocd -v
    - openocd -v 2>&1 | head -1 | grep -q -v dirty
    - openocd -v 2>&1 | head -1 | grep -q -- "-[0-9][0-9][0-9][0-9][0-9]-[0-9a-z]\+ "

about:
  home: http://openocd.org/
  license: GPLv2+
  summary: 'OpenOCD provides on-chip programming and debugging support with a layered architecture of JTAG interface and TAP support'
