package:
  name: openocd
  version: 0.9.0

source:
  fn: openocd-0.9.0.tar.bz2
  url: http://sourceforge.net/projects/openocd/files/openocd/0.9.0/openocd-0.9.0.tar.bz2/download
  sha256: 837042ac9a156b9363cbffa1fcdaf463bfb83a49331addf52e63119642b5f443

build:
  number: 0

requirements:
  build:
    - ncurses
    - boost
  run:
    - ncurses
    - boost

about:
  home: http://openocd.org/
  license: GPL
  summary: 'Free and Open On-Chip Debugging, In-System Programming and Boundary-Scan Testing'
