language: python
python:
  - "3.5"

sudo: false

install:
  - pip install pexpect
  - ./get-conda.sh
  - export PATH="$PATH:$HOME/conda/bin"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

env:
  - PACKAGE=binutils-lm32-elf
  - PACKAGE=gcc-lm32-elf
  - PACKAGE=sdcc
  - PACKAGE=openocd

script:
  - python ./.travis-output.py output.log conda build $PACKAGE
  - conda install $PACKAGE --use-local

after_failure:
  - cat output.log
