language: python
python:
  - "3.5"

sudo: false
addons:
  apt:
    packages:
    - texinfo
    - libftdi-dev
    - libusb-1.0-0-dev

install:
  - pip install pexpect
  - ./get-conda.sh
  - export PATH="$PATH:$HOME/conda/bin"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a

env:
  - PACKAGE=binutils-lm32-elf
  - PACKAGE=binutils-or1k-elf
  - PACKAGE=gcc-lm32-elf
  - PACKAGE=sdcc
  - PACKAGE=openocd

script:
  - python ./.travis-output.py output.log conda build $PACKAGE
  - conda install $PACKAGE --use-local
  - du -h ~/conda/conda-bld/linux-64/*

after_failure:
  - cat output.log

after_success:
  - if [ x$TRAVIS_BRANCH = x"master" ]; then anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USER ~/conda/conda-bld/linux-64/$PACKAGE*.tar.bz2; fi

matrix:
  allow_failures:
    - env: PACKAGE=sdcc

