language: c
cache: ccache
cache:
  directories:
   - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/git_cache
   - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/src_cache

sudo: false
addons:
  apt:
    packages:
    - texinfo
    - libftdi-dev
    - libusb-1.0-0-dev

install:
  - git submodule update --recursive --init
  - git submodule foreach git submodule update --recursive --init
  - export BASE_PATH=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path
  - export CONDA_PATH=$BASE_PATH/conda
  - mkdir -p $BASE_PATH
  - ./get-conda.sh $CONDA_PATH
  - export PATH="$PATH:$CONDA_PATH/bin"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install pexpect
  - conda info -a
  - conda config --add channels timvideos
  - conda clean -s --dry-run

env:
  # lm32 toolchain
  - PACKAGE=lm32/binutils
  #- PACKAGE=lm32/gcc-nostdc
  #- PACKAGE=lm32/gcc-newlib
  #- PACKAGE=lm32/gdb
  # or1k toolchain
  #- PACKAGE=lm32/binutils
  #- PACKAGE=lm32/gcc-nostdc
  #- PACKAGE=lm32/gcc-newlib
  #- PACKAGE=lm32/gdb
  # riscv32 toolchain
  #- PACKAGE=riscv32/binutils
  # sh2 toolchain
  #- PACKAGE=sh2/binutils
  # fx2 toolchain
  #- PACKAGE=sdcc
  # tools
  #- PACKAGE=openocd
  #- PACKAGE=verilator
  #- PACKAGE=flterm

script:
  - $CONDA_PATH/bin/python ./.travis-output.py output.log conda build $PACKAGE
  - conda install $CONDA_PATH/conda-bld/linux-64/*$(basename $PACKAGE)*.tar.bz2
  - du -h $CONDA_PATH/conda-bld/linux-64/*$(basename $PACKAGE)*.tar.bz2
  - conda clean -s --dry-run

after_failure:
  - cat output.log

after_success:
  - tar -jtf $CONDA_PATH/conda-bld/linux-64/*$(basename $PACKAGE)*.tar.bz2
    #- if [ x$TRAVIS_BRANCH = x"master" ]; then anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USER $CONDA_PATH/conda-bld/linux-64/*$(basename $PACKAGE)*.tar.bz2; fi

matrix:
  allow_failures:
    - env: PACKAGE=sdcc

