language: python
python:
  - "3.5"

sudo: false

install:
  - pip install pexpect
  - ./get-conda.sh
  - export PATH="$PATH:$HOME/conda/bin"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

script:
  - echo -n "travis_fold:start:binutils-lm32-elf\r"
  # binutils-lm32-elf
  - python ./.travis-output.py output.log.binutils conda build binutils-lm32-elf
  - conda install binutils-lm32-elf --use-local
  - echo -n "travis_fold:end:binutils-lm32-elf\r"
  # gcc-lm32-elf
  - echo -n "travis_fold:start:gcc-lm32-elf\r"
  - python ./.travis-output.py output.log.gcc conda build gcc-lm32-elf
  - conda install gcc-lm32-elf --use-local
  - echo -n "travis_fold:end:gcc-lm32-elf\r"
  # sdcc
  - echo -n "travis_fold:start:sdcc\r"
  - python ./.travis-output.py output.log.sdcc conda build sdcc
  - conda install sdcc --use-local
  - echo -n "travis_fold:end:sdcc\r"

after_failure:
  - cat output.log.*
