language: c

cache:
  ccache: true
  directories:
   - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/git_cache
   - /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/src_cache
before_cache:
  - ./.travis/before_cache.sh

#dist: trusty
sudo: false
addons:
  apt:
    packages:
    - autoconf
    - automake
    - build-essential
    - gperf
    - libftdi-dev
    - libudev1
    - libudev-dev
    - libusb-1.0-0-dev
    - libusb-dev
    - texinfo

before_install:
 - source .travis/common.sh

install:
 - ./.travis/install.sh

env:
  # lm32 toolchain
  - PACKAGE=lm32/binutils
  - PACKAGE=lm32/gcc-nostdc
  - PACKAGE=lm32/gcc-newlib
  - PACKAGE=lm32/gdb
  # or1k toolchain
  - PACKAGE=or1k/binutils
  - PACKAGE=or1k/gcc-nostdc
  - PACKAGE=or1k/gcc-newlib
  - PACKAGE=or1k/gdb
  # riscv32 toolchain
  - PACKAGE=riscv32/binutils
  # sh2 toolchain
  - PACKAGE=sh2/binutils
  # fx2 toolchain
  - PACKAGE=sdcc
  # tools
  - PACKAGE=openocd
  - PACKAGE=flterm
  # verilog tools
  - PACKAGE=iverilog            DATESHORT=1
  - PACKAGE=verilator
  - PACKAGE=vtr                 DATESHORT=1
  - PACKAGE=yosys               DATESHORT=1

script:
  - ./.travis/script.sh

after_failure:
  - ./.travis/after_failure.sh

after_success:
  - ./.travis/after_success.sh
