language: python
python:
  - "3.5"

sudo: false
addons:
  apt:
    packages:
    - texinfo
    - libftdi-dev
    - libusb-1.0-0-dev

install:
  - git submodule update --recursive --init
  - git submodule foreach git submodule update --recursive --init
  - export BASE_PATH=/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path
  - export CONDA_PATH=$BASE_PATH/conda
  - mkdir -p $BASE_PATH
  - pip install pexpect
  - ./get-conda.sh $CONDA_PATH
  - export PATH="$PATH:$CONDA_PATH/bin"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda config --add channels timvideos

env:
  - PACKAGE=binutils-lm32-elf
  - PACKAGE=binutils-or1k-elf
  - PACKAGE=gcc-lm32-elf
  - PACKAGE=gcc-or1k-elf
  - PACKAGE=sdcc
  - PACKAGE=openocd

script:
  - python ./.travis-output.py output.log conda build $PACKAGE
  - conda install $CONDA_PATH/conda-bld/linux-64/$PACKAGE*.tar.bz2
  - du -h $CONDA_PATH/conda-bld/linux-64/$PACKAGE*.tar.bz2

after_failure:
  - cat output.log

after_success:
  - tar -jtf $CONDA_PATH/conda-bld/linux-64/$PACKAGE*.tar.bz2
  - if [ x$TRAVIS_BRANCH = x"master" ]; then anaconda -t $ANACONDA_TOKEN upload --user $ANACONDA_USER $CONDA_PATH/conda-bld/linux-64/$PACKAGE*.tar.bz2; fi

matrix:
  allow_failures:
    - env: PACKAGE=sdcc

