language: c

sudo: false

install:
  - ./get-conda.sh
  - export PATH="$HOME/conda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

script:
  - conda build binutils-lm32-elf
  - conda install binutils-lm32-elf --use-local
  - conda build gcc-lm32-elf
  - conda install gcc-lm32-elf --use-local
