{% set version = '%s_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v','') or '0.X.X', GIT_DESCRIBE_NUMBER|int,   GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: uhdm-integration
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/alainmarcel/uhdm-integration.git

build:
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - cmake
    - pkg-config
    - libuuid
    - gperftools
    - flex
    - libunwind
    - swig

outputs:
    - name: surelog-uhdm
      script: surelog-flow.sh
      requirements:
          run:
              - python {{ python }}
              - gperftools
              - libunwind
      test:
          commands:
              - surelog-uhdm --version
    - name: verilator-uhdm
      script: verilator-flow.sh
      requirements:
          run:
              - {{ compiler('cxx') }}
              - bison
              - flex
              - ncurses
      test:
          commands:
              - verilator-uhdm --version
    - name: yosys-uhdm
      script: yosys-flow.sh
      requirements:
          run:
              - readline
      test:
          commands:
              - yosys-uhdm --version
    # empty meta-packages with dependencies only
    - name: uhdm-integration-verilator
      requirements:
          run:
              - surelog-uhdm {{version}}
              - verilator-uhdm {{version}}
    - name: uhdm-integration-yosys
      requirements:
          run:
              - surelog-uhdm {{version}}
              - yosys-uhdm {{version}}
