package:
  name: gcc-lm32-elf
  version: 5.3.0

source:
  fn: gcc-5.3.0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
  sha256: b84f5592e9218b73dbae612b5253035a7b34a9a1f7688d2e1bfaaf7267d5c4db

build:
  detect_binary_files_with_prefix: True
  number: 1

requirements:
  build:
    # These are taken from the output of the configure scripts
    - binutils-lm32-elf
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl >=0.15
    - cloog
  run:
    - binutils-lm32-elf
    - gmp >=4.3.2
    - mpfr >=2.4.2
    - mpc >=0.8.1
    - isl 0.12.2
    - cloog

test:
  commands:
    - lm32-elf-gcc --version
    - lm32-elf-gcc --version 2>&1 | grep -q 5.3.0
    - lm32-elf-gcc-5.3.0 --version

about:
  home: https://gcc.gnu.org/
  license: GPL
  summary: 'The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Java, Ada, and Go, as well as libraries for these languages (libstdc++, libgcj,...).'
