package:
  name: surelog
  version: {{ GIT_FULL_HASH }}

source:
  git_url: https://github.com/alainmarcel/Surelog
  git_rev: master

build:
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - python {{ python }}
    - gperftools
    - tk
    - libunwind
    
  run:
    - python

about:
  home: https://github.com/alainmarcel/Surelog
  license: Apache
  license_file: LICENSE
  summary: 'Parser/Compiler for SystemVerilog'
