package:
  name: gdb-or1k-elf
  version: git

source:
  git_url: https://github.com/openrisc/binutils-gdb.git
  git_rev: b853c77de9a3e23964e01fa71a96e3757827fda1

build:
  detect_binary_files_with_prefix: True
  number: 0

requirements:
  build:
    - system # [not win]
    - binutils-or1k-elf
    - gcc-or1k-elf

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL
  summary: 'GDB, the GNU Project debugger, allows you to see what is going on "inside" another program while it executes -- or what another program was doing at the moment it crashed.'
