package:
  name: slang
  version: {{ GIT_FULL_HASH }}

source:
  git_url: https://github.com/MikePopoloski/slang
  git_rev: master
  patches:
    - static-build.patch

build:
  # number: 201803050325
  number: {{ environ.get('DATE_NUM') }}
  # string: 20180305_0325
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - make
    - cmake
    - conan
about:
  home: https://github.com/MikePopoloski/slang
  license: MIT
  license_file: LICENSE
  summary: 'Parser and compiler library for SystemVerilog'
