package:
  name: gdb-lm32-elf
  version: 7.11

source:
  fn: gdb-7.11.tar.gz
  url: http://ftp.gnu.org/gnu/gdb/gdb-7.11.tar.gz
  sha256: 9382f5534aa0754169e1e09b5f1a3b77d1fa8c59c1e57617e06af37cb29c669a

build:
  detect_binary_files_with_prefix: True
  number: 0
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - system # [not win]
    - binutils-lm32-elf
    - gcc-lm32-elf-nostdc

test:
  commands:
    - lm32-elf-gdb --version
    - lm32-elf-gdb --version 2>&1 | grep -q 7.11

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL
  summary: 'GDB, the GNU Project debugger, allows you to see what is going on "inside" another program while it executes -- or what another program was doing at the moment it crashed.'
