package:
  name: iverilog
  version: git

source:
  git_url: https://github.com/steveicarus/iverilog.git

build:
  number: 1

requirements:
  build:
    - readline
    - gcc
  run:
    - readline

about:
  home: http://iverilog.icarus.com/
  license: ISC
  summary: 'Icarus Verilog (iverilog) is a Verilog simulation and synthesis tool. It operates as a compiler, compiling source code written in Verilog (IEEE-1364) into some target format. For batch simulation, the compiler can generate an intermediate form called vvp assembly. This intermediate form is executed by the ``vvp'' command. For synthesis, the compiler generates netlists in the desired format.'
