package:
  name: gdb-or1k-elf
  version: git

source:
  git_url: https://github.com/openrisc/binutils-gdb.git
  git_rev: gdb-7.11-or1k-release

build:
  detect_binary_files_with_prefix: True
  number: 0
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - system # [not win]
    - binutils-or1k-elf
    - gcc-lm32-elf-nostdc

test:
  commands:
    - or1k-elf-gdb --version
    - or1k-elf-gdb --version 2>&1 | grep -q 7.11

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL
  summary: 'GDB, the GNU Project debugger, allows you to see what is going on "inside" another program while it executes -- or what another program was doing at the moment it crashed.'
