package:
  name: flterm
  version: git

source:
  git_url: https://github.com/timvideos/flterm.git

build:
  number: 0

test:
  commands:
    - flterm --help

about:
  home: https://github.com/timvideos/flterm
  license: GPLv3
  summary: 'Serial boot program for MiSoC'
